// GenerateResources.csx
// Run with: dotnet script GenerateResources.csx -- <AssetsFolder> <OutputPath> <RootNamespace>
// Or invoke as an MSBuild pre-build target (see notes below).

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

string assetsFolder = Args.Count > 0 ? Args[0] : "Assets";
string outputPath   = Args.Count > 1 ? Args[1] : "Resources.cs";
string rootNamespace = Args.Count > 2 ? Args[2] : "ZeldaMsgPreview";

if (!Directory.Exists(assetsFolder))
{
    Console.Error.WriteLine($"Assets folder not found: {assetsFolder}");
    return;
}

var imageExtensions = new[] { ".png", ".bmp", ".jpg", ".jpeg" };

var files = Directory.GetFiles(assetsFolder, "*.*", SearchOption.AllDirectories)
    .Where(f => imageExtensions.Contains(Path.GetExtension(f).ToLowerInvariant()))
    .OrderBy(f => f)
    .ToList();

string SanitizeIdentifier(string name)
{
    var sb = new StringBuilder();
    foreach (char c in name)
        sb.Append(char.IsLetterOrDigit(c) ? c : '_');

    var result = sb.ToString();
    if (result.Length == 0 || char.IsDigit(result[0]))
        result = "_" + result;

    return result;
}

var sbOut = new StringBuilder();
sbOut.AppendLine("// <auto-generated>");
sbOut.AppendLine("// This file is generated by GenerateResources.csx. Do not edit by hand -");
sbOut.AppendLine("// re-run the generator instead, or your changes will be overwritten.");
sbOut.AppendLine("// </auto-generated>");
sbOut.AppendLine("using SkiaSharp;");
sbOut.AppendLine("using System.IO;");
sbOut.AppendLine("using System.Reflection;");
sbOut.AppendLine();
sbOut.AppendLine($"namespace {rootNamespace}");
sbOut.AppendLine("{");
sbOut.AppendLine("    internal static class Resources");
sbOut.AppendLine("    {");
string assetsFolderName = Path.GetFileName(assetsFolder.TrimEnd('/', '\\'));
sbOut.AppendLine($"        private const string ResourceRoot = \"{rootNamespace}.{assetsFolderName}.\";");
sbOut.AppendLine();
sbOut.AppendLine("        private static SKBitmap LoadEmbedded(string name)");
sbOut.AppendLine("        {");
sbOut.AppendLine("            var assembly = Assembly.GetExecutingAssembly();");
sbOut.AppendLine("            using (Stream stream = assembly.GetManifestResourceStream(ResourceRoot + name))");
sbOut.AppendLine("            {");
sbOut.AppendLine("                if (stream == null)");
sbOut.AppendLine("                    throw new FileNotFoundException($\"Embedded resource '{ResourceRoot + name}' not found.\");");
sbOut.AppendLine();
sbOut.AppendLine("                return SKBitmap.Decode(stream);");
sbOut.AppendLine("            }");
sbOut.AppendLine("        }");
sbOut.AppendLine();

var seenNames = new HashSet<string>();
var nameToFile = new List<(string PropertyName, string FileName)>();

foreach (var file in files)
{
    string fileName = Path.GetFileName(file);
    string propertyName = SanitizeIdentifier(Path.GetFileNameWithoutExtension(file));

    if (!seenNames.Add(propertyName))
    {
        Console.Error.WriteLine($"WARNING: duplicate property name '{propertyName}' from file '{file}' - skipping.");
        continue;
    }

    nameToFile.Add((propertyName, fileName));
    sbOut.AppendLine($"        internal static SKBitmap {propertyName} => LoadEmbedded(\"{fileName}\");");
}

sbOut.AppendLine();
sbOut.AppendLine("        // Case-insensitive lookup by logical name (without extension), for call sites");
sbOut.AppendLine("        // that need to build the resource name dynamically at runtime rather than");
sbOut.AppendLine("        // referencing a fixed property. Returns null instead of throwing if not found.");
sbOut.AppendLine("        private static readonly System.Collections.Generic.Dictionary<string, string> NameLookup =");
sbOut.AppendLine("            new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase)");
sbOut.AppendLine("            {");
foreach (var (propertyName, fileName) in nameToFile)
{
    sbOut.AppendLine($"                {{ \"{propertyName}\", \"{fileName}\" }},");
}
sbOut.AppendLine("            };");
sbOut.AppendLine();
sbOut.AppendLine("        internal static SKBitmap TryGetBitmap(string logicalName)");
sbOut.AppendLine("        {");
sbOut.AppendLine("            if (!NameLookup.TryGetValue(logicalName, out string fileName))");
sbOut.AppendLine("                return null;");
sbOut.AppendLine();
sbOut.AppendLine("            try");
sbOut.AppendLine("            {");
sbOut.AppendLine("                return LoadEmbedded(fileName);");
sbOut.AppendLine("            }");
sbOut.AppendLine("            catch (FileNotFoundException)");
sbOut.AppendLine("            {");
sbOut.AppendLine("                return null;");
sbOut.AppendLine("            }");
sbOut.AppendLine("        }");

sbOut.AppendLine("    }");
sbOut.AppendLine("}");

File.WriteAllText(outputPath, sbOut.ToString());
Console.WriteLine($"Generated {files.Count} propert{(files.Count == 1 ? "y" : "ies")} in {outputPath}");
