// <auto-generated>
// This file is generated by GenerateResources.csx. Do not edit by hand -
// re-run the generator instead, or your changes will be overwritten.
// </auto-generated>
using SkiaSharp;
using System.IO;
using System.Reflection;

namespace ZeldaMsgPreview
{
    internal static class Resources
    {
        private const string ResourceRoot = "ZeldaMsgPreview.Assets.";

        private static SKBitmap LoadEmbedded(string name)
        {
            var assembly = Assembly.GetExecutingAssembly();
            using (Stream stream = assembly.GetManifestResourceStream(ResourceRoot + name))
            {
                if (stream == null)
                    throw new FileNotFoundException($"Embedded resource '{ResourceRoot + name}' not found.");

                return SKBitmap.Decode(stream);
            }
        }

        internal static SKBitmap Box_Arrow => LoadEmbedded("Box_Arrow.png");
        internal static SKBitmap Box_Blue => LoadEmbedded("Box_Blue.png");
        internal static SKBitmap Box_Default => LoadEmbedded("Box_Default.png");
        internal static SKBitmap Box_End => LoadEmbedded("Box_End.png");
        internal static SKBitmap Box_Staff => LoadEmbedded("Box_Staff.png");
        internal static SKBitmap Box_Triangle => LoadEmbedded("Box_Triangle.png");
        internal static SKBitmap Box_Wooden => LoadEmbedded("Box_Wooden.png");
        internal static SKBitmap char_20 => LoadEmbedded("char_20.png");
        internal static SKBitmap char_21 => LoadEmbedded("char_21.png");
        internal static SKBitmap char_22 => LoadEmbedded("char_22.png");
        internal static SKBitmap char_23 => LoadEmbedded("char_23.png");
        internal static SKBitmap char_24 => LoadEmbedded("char_24.png");
        internal static SKBitmap char_25 => LoadEmbedded("char_25.png");
        internal static SKBitmap char_26 => LoadEmbedded("char_26.png");
        internal static SKBitmap char_27 => LoadEmbedded("char_27.png");
        internal static SKBitmap char_28 => LoadEmbedded("char_28.png");
        internal static SKBitmap char_29 => LoadEmbedded("char_29.png");
        internal static SKBitmap char_2a => LoadEmbedded("char_2a.png");
        internal static SKBitmap char_2b => LoadEmbedded("char_2b.png");
        internal static SKBitmap char_2c => LoadEmbedded("char_2c.png");
        internal static SKBitmap char_2d => LoadEmbedded("char_2d.png");
        internal static SKBitmap char_2e => LoadEmbedded("char_2e.png");
        internal static SKBitmap char_2f => LoadEmbedded("char_2f.png");
        internal static SKBitmap char_30 => LoadEmbedded("char_30.png");
        internal static SKBitmap char_31 => LoadEmbedded("char_31.png");
        internal static SKBitmap char_32 => LoadEmbedded("char_32.png");
        internal static SKBitmap char_33 => LoadEmbedded("char_33.png");
        internal static SKBitmap char_34 => LoadEmbedded("char_34.png");
        internal static SKBitmap char_35 => LoadEmbedded("char_35.png");
        internal static SKBitmap char_36 => LoadEmbedded("char_36.png");
        internal static SKBitmap char_37 => LoadEmbedded("char_37.png");
        internal static SKBitmap char_38 => LoadEmbedded("char_38.png");
        internal static SKBitmap char_39 => LoadEmbedded("char_39.png");
        internal static SKBitmap char_3a => LoadEmbedded("char_3a.png");
        internal static SKBitmap char_3b => LoadEmbedded("char_3b.png");
        internal static SKBitmap char_3c => LoadEmbedded("char_3c.png");
        internal static SKBitmap char_3d => LoadEmbedded("char_3d.png");
        internal static SKBitmap char_3e => LoadEmbedded("char_3e.png");
        internal static SKBitmap char_3f => LoadEmbedded("char_3f.png");
        internal static SKBitmap char_40 => LoadEmbedded("char_40.png");
        internal static SKBitmap char_41 => LoadEmbedded("char_41.png");
        internal static SKBitmap char_42 => LoadEmbedded("char_42.png");
        internal static SKBitmap char_43 => LoadEmbedded("char_43.png");
        internal static SKBitmap char_44 => LoadEmbedded("char_44.png");
        internal static SKBitmap char_45 => LoadEmbedded("char_45.png");
        internal static SKBitmap char_46 => LoadEmbedded("char_46.png");
        internal static SKBitmap char_47 => LoadEmbedded("char_47.png");
        internal static SKBitmap char_48 => LoadEmbedded("char_48.png");
        internal static SKBitmap char_49 => LoadEmbedded("char_49.png");
        internal static SKBitmap char_4a => LoadEmbedded("char_4a.png");
        internal static SKBitmap char_4b => LoadEmbedded("char_4b.png");
        internal static SKBitmap char_4c => LoadEmbedded("char_4c.png");
        internal static SKBitmap char_4d => LoadEmbedded("char_4d.png");
        internal static SKBitmap char_4e => LoadEmbedded("char_4e.png");
        internal static SKBitmap char_4f => LoadEmbedded("char_4f.png");
        internal static SKBitmap char_50 => LoadEmbedded("char_50.png");
        internal static SKBitmap char_51 => LoadEmbedded("char_51.png");
        internal static SKBitmap char_52 => LoadEmbedded("char_52.png");
        internal static SKBitmap char_53 => LoadEmbedded("char_53.png");
        internal static SKBitmap char_54 => LoadEmbedded("char_54.png");
        internal static SKBitmap char_55 => LoadEmbedded("char_55.png");
        internal static SKBitmap char_56 => LoadEmbedded("char_56.png");
        internal static SKBitmap char_57 => LoadEmbedded("char_57.png");
        internal static SKBitmap char_58 => LoadEmbedded("char_58.png");
        internal static SKBitmap char_59 => LoadEmbedded("char_59.png");
        internal static SKBitmap char_5a => LoadEmbedded("char_5a.png");
        internal static SKBitmap char_5b => LoadEmbedded("char_5b.png");
        internal static SKBitmap char_5c => LoadEmbedded("char_5c.png");
        internal static SKBitmap char_5d => LoadEmbedded("char_5d.png");
        internal static SKBitmap char_5e => LoadEmbedded("char_5e.png");
        internal static SKBitmap char_5f => LoadEmbedded("char_5f.png");
        internal static SKBitmap char_60 => LoadEmbedded("char_60.png");
        internal static SKBitmap char_61 => LoadEmbedded("char_61.png");
        internal static SKBitmap char_62 => LoadEmbedded("char_62.png");
        internal static SKBitmap char_63 => LoadEmbedded("char_63.png");
        internal static SKBitmap char_64 => LoadEmbedded("char_64.png");
        internal static SKBitmap char_65 => LoadEmbedded("char_65.png");
        internal static SKBitmap char_66 => LoadEmbedded("char_66.png");
        internal static SKBitmap char_67 => LoadEmbedded("char_67.png");
        internal static SKBitmap char_68 => LoadEmbedded("char_68.png");
        internal static SKBitmap char_69 => LoadEmbedded("char_69.png");
        internal static SKBitmap char_6a => LoadEmbedded("char_6a.png");
        internal static SKBitmap char_6b => LoadEmbedded("char_6b.png");
        internal static SKBitmap char_6c => LoadEmbedded("char_6c.png");
        internal static SKBitmap char_6d => LoadEmbedded("char_6d.png");
        internal static SKBitmap char_6e => LoadEmbedded("char_6e.png");
        internal static SKBitmap char_6f => LoadEmbedded("char_6f.png");
        internal static SKBitmap char_70 => LoadEmbedded("char_70.png");
        internal static SKBitmap char_71 => LoadEmbedded("char_71.png");
        internal static SKBitmap char_72 => LoadEmbedded("char_72.png");
        internal static SKBitmap char_73 => LoadEmbedded("char_73.png");
        internal static SKBitmap char_74 => LoadEmbedded("char_74.png");
        internal static SKBitmap char_75 => LoadEmbedded("char_75.png");
        internal static SKBitmap char_76 => LoadEmbedded("char_76.png");
        internal static SKBitmap char_77 => LoadEmbedded("char_77.png");
        internal static SKBitmap char_78 => LoadEmbedded("char_78.png");
        internal static SKBitmap char_79 => LoadEmbedded("char_79.png");
        internal static SKBitmap char_7a => LoadEmbedded("char_7a.png");
        internal static SKBitmap char_7b => LoadEmbedded("char_7b.png");
        internal static SKBitmap char_7c => LoadEmbedded("char_7c.png");
        internal static SKBitmap char_7d => LoadEmbedded("char_7d.png");
        internal static SKBitmap char_7e => LoadEmbedded("char_7e.png");
        internal static SKBitmap char_7f => LoadEmbedded("char_7f.png");
        internal static SKBitmap char_80 => LoadEmbedded("char_80.png");
        internal static SKBitmap char_81 => LoadEmbedded("char_81.png");
        internal static SKBitmap char_82 => LoadEmbedded("char_82.png");
        internal static SKBitmap char_83 => LoadEmbedded("char_83.png");
        internal static SKBitmap char_84 => LoadEmbedded("char_84.png");
        internal static SKBitmap char_85 => LoadEmbedded("char_85.png");
        internal static SKBitmap char_86 => LoadEmbedded("char_86.png");
        internal static SKBitmap char_87 => LoadEmbedded("char_87.png");
        internal static SKBitmap char_88 => LoadEmbedded("char_88.png");
        internal static SKBitmap char_89 => LoadEmbedded("char_89.png");
        internal static SKBitmap char_8a => LoadEmbedded("char_8a.png");
        internal static SKBitmap char_8b => LoadEmbedded("char_8b.png");
        internal static SKBitmap char_8c => LoadEmbedded("char_8c.png");
        internal static SKBitmap char_8d => LoadEmbedded("char_8d.png");
        internal static SKBitmap char_8e => LoadEmbedded("char_8e.png");
        internal static SKBitmap char_8f => LoadEmbedded("char_8f.png");
        internal static SKBitmap char_90 => LoadEmbedded("char_90.png");
        internal static SKBitmap char_91 => LoadEmbedded("char_91.png");
        internal static SKBitmap char_92 => LoadEmbedded("char_92.png");
        internal static SKBitmap char_93 => LoadEmbedded("char_93.png");
        internal static SKBitmap char_94 => LoadEmbedded("char_94.png");
        internal static SKBitmap char_95 => LoadEmbedded("char_95.png");
        internal static SKBitmap char_96 => LoadEmbedded("char_96.png");
        internal static SKBitmap char_97 => LoadEmbedded("char_97.png");
        internal static SKBitmap char_98 => LoadEmbedded("char_98.png");
        internal static SKBitmap char_99 => LoadEmbedded("char_99.png");
        internal static SKBitmap char_9a => LoadEmbedded("char_9a.png");
        internal static SKBitmap char_9b => LoadEmbedded("char_9b.png");
        internal static SKBitmap char_9c => LoadEmbedded("char_9c.png");
        internal static SKBitmap char_9d => LoadEmbedded("char_9d.png");
        internal static SKBitmap char_9e => LoadEmbedded("char_9e.png");
        internal static SKBitmap char_9f => LoadEmbedded("char_9f.png");
        internal static SKBitmap char_a0 => LoadEmbedded("char_a0.png");
        internal static SKBitmap char_a1 => LoadEmbedded("char_a1.png");
        internal static SKBitmap char_a2 => LoadEmbedded("char_a2.png");
        internal static SKBitmap char_a3 => LoadEmbedded("char_a3.png");
        internal static SKBitmap char_a4 => LoadEmbedded("char_a4.png");
        internal static SKBitmap char_a5 => LoadEmbedded("char_a5.png");
        internal static SKBitmap char_a6 => LoadEmbedded("char_a6.png");
        internal static SKBitmap char_a7 => LoadEmbedded("char_a7.png");
        internal static SKBitmap char_a8 => LoadEmbedded("char_a8.png");
        internal static SKBitmap char_a9 => LoadEmbedded("char_a9.png");
        internal static SKBitmap char_aa => LoadEmbedded("char_aa.png");
        internal static SKBitmap char_ab => LoadEmbedded("char_ab.png");
        internal static SKBitmap Fading_Box => LoadEmbedded("Fading_Box.png");
        internal static SKBitmap Fading_Box1 => LoadEmbedded("Fading_Box1.png");
        internal static SKBitmap icon_0 => LoadEmbedded("icon_0.png");
        internal static SKBitmap icon_1 => LoadEmbedded("icon_1.png");
        internal static SKBitmap icon_10 => LoadEmbedded("icon_10.png");
        internal static SKBitmap icon_102 => LoadEmbedded("icon_102.png");
        internal static SKBitmap icon_103 => LoadEmbedded("icon_103.png");
        internal static SKBitmap icon_104 => LoadEmbedded("icon_104.png");
        internal static SKBitmap icon_105 => LoadEmbedded("icon_105.png");
        internal static SKBitmap icon_106 => LoadEmbedded("icon_106.png");
        internal static SKBitmap icon_107 => LoadEmbedded("icon_107.png");
        internal static SKBitmap icon_108 => LoadEmbedded("icon_108.png");
        internal static SKBitmap icon_109 => LoadEmbedded("icon_109.png");
        internal static SKBitmap icon_11 => LoadEmbedded("icon_11.png");
        internal static SKBitmap icon_110 => LoadEmbedded("icon_110.png");
        internal static SKBitmap icon_111 => LoadEmbedded("icon_111.png");
        internal static SKBitmap icon_112 => LoadEmbedded("icon_112.png");
        internal static SKBitmap icon_113 => LoadEmbedded("icon_113.png");
        internal static SKBitmap icon_114 => LoadEmbedded("icon_114.png");
        internal static SKBitmap icon_115 => LoadEmbedded("icon_115.png");
        internal static SKBitmap icon_116 => LoadEmbedded("icon_116.png");
        internal static SKBitmap icon_117 => LoadEmbedded("icon_117.png");
        internal static SKBitmap icon_118 => LoadEmbedded("icon_118.png");
        internal static SKBitmap icon_119 => LoadEmbedded("icon_119.png");
        internal static SKBitmap icon_12 => LoadEmbedded("icon_12.png");
        internal static SKBitmap icon_120 => LoadEmbedded("icon_120.png");
        internal static SKBitmap icon_121 => LoadEmbedded("icon_121.png");
        internal static SKBitmap icon_13 => LoadEmbedded("icon_13.png");
        internal static SKBitmap icon_14 => LoadEmbedded("icon_14.png");
        internal static SKBitmap icon_15 => LoadEmbedded("icon_15.png");
        internal static SKBitmap icon_16 => LoadEmbedded("icon_16.png");
        internal static SKBitmap icon_17 => LoadEmbedded("icon_17.png");
        internal static SKBitmap icon_18 => LoadEmbedded("icon_18.png");
        internal static SKBitmap icon_19 => LoadEmbedded("icon_19.png");
        internal static SKBitmap icon_2 => LoadEmbedded("icon_2.png");
        internal static SKBitmap icon_20 => LoadEmbedded("icon_20.png");
        internal static SKBitmap icon_21 => LoadEmbedded("icon_21.png");
        internal static SKBitmap icon_22 => LoadEmbedded("icon_22.png");
        internal static SKBitmap icon_23 => LoadEmbedded("icon_23.png");
        internal static SKBitmap icon_24 => LoadEmbedded("icon_24.png");
        internal static SKBitmap icon_25 => LoadEmbedded("icon_25.png");
        internal static SKBitmap icon_26 => LoadEmbedded("icon_26.png");
        internal static SKBitmap icon_27 => LoadEmbedded("icon_27.png");
        internal static SKBitmap icon_28 => LoadEmbedded("icon_28.png");
        internal static SKBitmap icon_29 => LoadEmbedded("icon_29.png");
        internal static SKBitmap icon_3 => LoadEmbedded("icon_3.png");
        internal static SKBitmap icon_30 => LoadEmbedded("icon_30.png");
        internal static SKBitmap icon_31 => LoadEmbedded("icon_31.png");
        internal static SKBitmap icon_32 => LoadEmbedded("icon_32.png");
        internal static SKBitmap icon_33 => LoadEmbedded("icon_33.png");
        internal static SKBitmap icon_34 => LoadEmbedded("icon_34.png");
        internal static SKBitmap icon_35 => LoadEmbedded("icon_35.png");
        internal static SKBitmap icon_36 => LoadEmbedded("icon_36.png");
        internal static SKBitmap icon_37 => LoadEmbedded("icon_37.png");
        internal static SKBitmap icon_38 => LoadEmbedded("icon_38.png");
        internal static SKBitmap icon_39 => LoadEmbedded("icon_39.png");
        internal static SKBitmap icon_4 => LoadEmbedded("icon_4.png");
        internal static SKBitmap icon_40 => LoadEmbedded("icon_40.png");
        internal static SKBitmap icon_41 => LoadEmbedded("icon_41.png");
        internal static SKBitmap icon_42 => LoadEmbedded("icon_42.png");
        internal static SKBitmap icon_43 => LoadEmbedded("icon_43.png");
        internal static SKBitmap icon_44 => LoadEmbedded("icon_44.png");
        internal static SKBitmap icon_45 => LoadEmbedded("icon_45.png");
        internal static SKBitmap icon_46 => LoadEmbedded("icon_46.png");
        internal static SKBitmap icon_47 => LoadEmbedded("icon_47.png");
        internal static SKBitmap icon_48 => LoadEmbedded("icon_48.png");
        internal static SKBitmap icon_49 => LoadEmbedded("icon_49.png");
        internal static SKBitmap icon_5 => LoadEmbedded("icon_5.png");
        internal static SKBitmap icon_50 => LoadEmbedded("icon_50.png");
        internal static SKBitmap icon_51 => LoadEmbedded("icon_51.png");
        internal static SKBitmap icon_52 => LoadEmbedded("icon_52.png");
        internal static SKBitmap icon_53 => LoadEmbedded("icon_53.png");
        internal static SKBitmap icon_54 => LoadEmbedded("icon_54.png");
        internal static SKBitmap icon_55 => LoadEmbedded("icon_55.png");
        internal static SKBitmap icon_56 => LoadEmbedded("icon_56.png");
        internal static SKBitmap icon_57 => LoadEmbedded("icon_57.png");
        internal static SKBitmap icon_58 => LoadEmbedded("icon_58.png");
        internal static SKBitmap icon_59 => LoadEmbedded("icon_59.png");
        internal static SKBitmap icon_6 => LoadEmbedded("icon_6.png");
        internal static SKBitmap icon_60 => LoadEmbedded("icon_60.png");
        internal static SKBitmap icon_61 => LoadEmbedded("icon_61.png");
        internal static SKBitmap icon_62 => LoadEmbedded("icon_62.png");
        internal static SKBitmap icon_63 => LoadEmbedded("icon_63.png");
        internal static SKBitmap icon_64 => LoadEmbedded("icon_64.png");
        internal static SKBitmap icon_65 => LoadEmbedded("icon_65.png");
        internal static SKBitmap icon_66 => LoadEmbedded("icon_66.png");
        internal static SKBitmap icon_67 => LoadEmbedded("icon_67.png");
        internal static SKBitmap icon_68 => LoadEmbedded("icon_68.png");
        internal static SKBitmap icon_69 => LoadEmbedded("icon_69.png");
        internal static SKBitmap icon_7 => LoadEmbedded("icon_7.png");
        internal static SKBitmap icon_70 => LoadEmbedded("icon_70.png");
        internal static SKBitmap icon_71 => LoadEmbedded("icon_71.png");
        internal static SKBitmap icon_72 => LoadEmbedded("icon_72.png");
        internal static SKBitmap icon_73 => LoadEmbedded("icon_73.png");
        internal static SKBitmap icon_74 => LoadEmbedded("icon_74.png");
        internal static SKBitmap icon_75 => LoadEmbedded("icon_75.png");
        internal static SKBitmap icon_76 => LoadEmbedded("icon_76.png");
        internal static SKBitmap icon_77 => LoadEmbedded("icon_77.png");
        internal static SKBitmap icon_78 => LoadEmbedded("icon_78.png");
        internal static SKBitmap icon_79 => LoadEmbedded("icon_79.png");
        internal static SKBitmap icon_8 => LoadEmbedded("icon_8.png");
        internal static SKBitmap icon_80 => LoadEmbedded("icon_80.png");
        internal static SKBitmap icon_81 => LoadEmbedded("icon_81.png");
        internal static SKBitmap icon_82 => LoadEmbedded("icon_82.png");
        internal static SKBitmap icon_83 => LoadEmbedded("icon_83.png");
        internal static SKBitmap icon_84 => LoadEmbedded("icon_84.png");
        internal static SKBitmap icon_85 => LoadEmbedded("icon_85.png");
        internal static SKBitmap icon_86 => LoadEmbedded("icon_86.png");
        internal static SKBitmap icon_87 => LoadEmbedded("icon_87.png");
        internal static SKBitmap icon_88 => LoadEmbedded("icon_88.png");
        internal static SKBitmap icon_89 => LoadEmbedded("icon_89.png");
        internal static SKBitmap icon_9 => LoadEmbedded("icon_9.png");
        internal static SKBitmap majora_Box_Arrow => LoadEmbedded("majora_Box_Arrow.png");
        internal static SKBitmap majora_Box_Bomber => LoadEmbedded("majora_Box_Bomber.png");
        internal static SKBitmap majora_Box_Default => LoadEmbedded("majora_Box_Default.png");
        internal static SKBitmap majora_Box_End => LoadEmbedded("majora_Box_End.png");
        internal static SKBitmap majora_Box_Staff => LoadEmbedded("majora_Box_Staff.png");
        internal static SKBitmap majora_Box_Triangle => LoadEmbedded("majora_Box_Triangle.png");
        internal static SKBitmap majora_Box_Wooden => LoadEmbedded("majora_Box_Wooden.png");
        internal static SKBitmap majora_char_20 => LoadEmbedded("majora_char_20.png");
        internal static SKBitmap majora_char_21 => LoadEmbedded("majora_char_21.png");
        internal static SKBitmap majora_char_22 => LoadEmbedded("majora_char_22.png");
        internal static SKBitmap majora_char_23 => LoadEmbedded("majora_char_23.png");
        internal static SKBitmap majora_char_24 => LoadEmbedded("majora_char_24.png");
        internal static SKBitmap majora_char_25 => LoadEmbedded("majora_char_25.png");
        internal static SKBitmap majora_char_26 => LoadEmbedded("majora_char_26.png");
        internal static SKBitmap majora_char_27 => LoadEmbedded("majora_char_27.png");
        internal static SKBitmap majora_char_28 => LoadEmbedded("majora_char_28.png");
        internal static SKBitmap majora_char_29 => LoadEmbedded("majora_char_29.png");
        internal static SKBitmap majora_char_2a => LoadEmbedded("majora_char_2a.png");
        internal static SKBitmap majora_char_2b => LoadEmbedded("majora_char_2b.png");
        internal static SKBitmap majora_char_2c => LoadEmbedded("majora_char_2c.png");
        internal static SKBitmap majora_char_2d => LoadEmbedded("majora_char_2d.png");
        internal static SKBitmap majora_char_2e => LoadEmbedded("majora_char_2e.png");
        internal static SKBitmap majora_char_2f => LoadEmbedded("majora_char_2f.png");
        internal static SKBitmap majora_char_30 => LoadEmbedded("majora_char_30.png");
        internal static SKBitmap majora_char_31 => LoadEmbedded("majora_char_31.png");
        internal static SKBitmap majora_char_32 => LoadEmbedded("majora_char_32.png");
        internal static SKBitmap majora_char_33 => LoadEmbedded("majora_char_33.png");
        internal static SKBitmap majora_char_34 => LoadEmbedded("majora_char_34.png");
        internal static SKBitmap majora_char_35 => LoadEmbedded("majora_char_35.png");
        internal static SKBitmap majora_char_36 => LoadEmbedded("majora_char_36.png");
        internal static SKBitmap majora_char_37 => LoadEmbedded("majora_char_37.png");
        internal static SKBitmap majora_char_38 => LoadEmbedded("majora_char_38.png");
        internal static SKBitmap majora_char_39 => LoadEmbedded("majora_char_39.png");
        internal static SKBitmap majora_char_3a => LoadEmbedded("majora_char_3a.png");
        internal static SKBitmap majora_char_3b => LoadEmbedded("majora_char_3b.png");
        internal static SKBitmap majora_char_3c => LoadEmbedded("majora_char_3c.png");
        internal static SKBitmap majora_char_3d => LoadEmbedded("majora_char_3d.png");
        internal static SKBitmap majora_char_3e => LoadEmbedded("majora_char_3e.png");
        internal static SKBitmap majora_char_3f => LoadEmbedded("majora_char_3f.png");
        internal static SKBitmap majora_char_40 => LoadEmbedded("majora_char_40.png");
        internal static SKBitmap majora_char_41 => LoadEmbedded("majora_char_41.png");
        internal static SKBitmap majora_char_42 => LoadEmbedded("majora_char_42.png");
        internal static SKBitmap majora_char_43 => LoadEmbedded("majora_char_43.png");
        internal static SKBitmap majora_char_44 => LoadEmbedded("majora_char_44.png");
        internal static SKBitmap majora_char_45 => LoadEmbedded("majora_char_45.png");
        internal static SKBitmap majora_char_46 => LoadEmbedded("majora_char_46.png");
        internal static SKBitmap majora_char_47 => LoadEmbedded("majora_char_47.png");
        internal static SKBitmap majora_char_48 => LoadEmbedded("majora_char_48.png");
        internal static SKBitmap majora_char_49 => LoadEmbedded("majora_char_49.png");
        internal static SKBitmap majora_char_4a => LoadEmbedded("majora_char_4a.png");
        internal static SKBitmap majora_char_4b => LoadEmbedded("majora_char_4b.png");
        internal static SKBitmap majora_char_4c => LoadEmbedded("majora_char_4c.png");
        internal static SKBitmap majora_char_4d => LoadEmbedded("majora_char_4d.png");
        internal static SKBitmap majora_char_4e => LoadEmbedded("majora_char_4e.png");
        internal static SKBitmap majora_char_4f => LoadEmbedded("majora_char_4f.png");
        internal static SKBitmap majora_char_50 => LoadEmbedded("majora_char_50.png");
        internal static SKBitmap majora_char_51 => LoadEmbedded("majora_char_51.png");
        internal static SKBitmap majora_char_52 => LoadEmbedded("majora_char_52.png");
        internal static SKBitmap majora_char_53 => LoadEmbedded("majora_char_53.png");
        internal static SKBitmap majora_char_54 => LoadEmbedded("majora_char_54.png");
        internal static SKBitmap majora_char_55 => LoadEmbedded("majora_char_55.png");
        internal static SKBitmap majora_char_56 => LoadEmbedded("majora_char_56.png");
        internal static SKBitmap majora_char_57 => LoadEmbedded("majora_char_57.png");
        internal static SKBitmap majora_char_58 => LoadEmbedded("majora_char_58.png");
        internal static SKBitmap majora_char_59 => LoadEmbedded("majora_char_59.png");
        internal static SKBitmap majora_char_5a => LoadEmbedded("majora_char_5a.png");
        internal static SKBitmap majora_char_5b => LoadEmbedded("majora_char_5b.png");
        internal static SKBitmap majora_char_5c => LoadEmbedded("majora_char_5c.png");
        internal static SKBitmap majora_char_5d => LoadEmbedded("majora_char_5d.png");
        internal static SKBitmap majora_char_5e => LoadEmbedded("majora_char_5e.png");
        internal static SKBitmap majora_char_5f => LoadEmbedded("majora_char_5f.png");
        internal static SKBitmap majora_char_60 => LoadEmbedded("majora_char_60.png");
        internal static SKBitmap majora_char_61 => LoadEmbedded("majora_char_61.png");
        internal static SKBitmap majora_char_62 => LoadEmbedded("majora_char_62.png");
        internal static SKBitmap majora_char_63 => LoadEmbedded("majora_char_63.png");
        internal static SKBitmap majora_char_64 => LoadEmbedded("majora_char_64.png");
        internal static SKBitmap majora_char_65 => LoadEmbedded("majora_char_65.png");
        internal static SKBitmap majora_char_66 => LoadEmbedded("majora_char_66.png");
        internal static SKBitmap majora_char_67 => LoadEmbedded("majora_char_67.png");
        internal static SKBitmap majora_char_68 => LoadEmbedded("majora_char_68.png");
        internal static SKBitmap majora_char_69 => LoadEmbedded("majora_char_69.png");
        internal static SKBitmap majora_char_6a => LoadEmbedded("majora_char_6a.png");
        internal static SKBitmap majora_char_6b => LoadEmbedded("majora_char_6b.png");
        internal static SKBitmap majora_char_6c => LoadEmbedded("majora_char_6c.png");
        internal static SKBitmap majora_char_6d => LoadEmbedded("majora_char_6d.png");
        internal static SKBitmap majora_char_6e => LoadEmbedded("majora_char_6e.png");
        internal static SKBitmap majora_char_6f => LoadEmbedded("majora_char_6f.png");
        internal static SKBitmap majora_char_70 => LoadEmbedded("majora_char_70.png");
        internal static SKBitmap majora_char_71 => LoadEmbedded("majora_char_71.png");
        internal static SKBitmap majora_char_72 => LoadEmbedded("majora_char_72.png");
        internal static SKBitmap majora_char_73 => LoadEmbedded("majora_char_73.png");
        internal static SKBitmap majora_char_74 => LoadEmbedded("majora_char_74.png");
        internal static SKBitmap majora_char_75 => LoadEmbedded("majora_char_75.png");
        internal static SKBitmap majora_char_76 => LoadEmbedded("majora_char_76.png");
        internal static SKBitmap majora_char_77 => LoadEmbedded("majora_char_77.png");
        internal static SKBitmap majora_char_78 => LoadEmbedded("majora_char_78.png");
        internal static SKBitmap majora_char_79 => LoadEmbedded("majora_char_79.png");
        internal static SKBitmap majora_char_7a => LoadEmbedded("majora_char_7a.png");
        internal static SKBitmap majora_char_7b => LoadEmbedded("majora_char_7b.png");
        internal static SKBitmap majora_char_7c => LoadEmbedded("majora_char_7c.png");
        internal static SKBitmap majora_char_7d => LoadEmbedded("majora_char_7d.png");
        internal static SKBitmap majora_char_7e => LoadEmbedded("majora_char_7e.png");
        internal static SKBitmap majora_char_7f => LoadEmbedded("majora_char_7f.png");
        internal static SKBitmap majora_char_80 => LoadEmbedded("majora_char_80.png");
        internal static SKBitmap majora_char_81 => LoadEmbedded("majora_char_81.png");
        internal static SKBitmap majora_char_82 => LoadEmbedded("majora_char_82.png");
        internal static SKBitmap majora_char_83 => LoadEmbedded("majora_char_83.png");
        internal static SKBitmap majora_char_84 => LoadEmbedded("majora_char_84.png");
        internal static SKBitmap majora_char_85 => LoadEmbedded("majora_char_85.png");
        internal static SKBitmap majora_char_86 => LoadEmbedded("majora_char_86.png");
        internal static SKBitmap majora_char_87 => LoadEmbedded("majora_char_87.png");
        internal static SKBitmap majora_char_88 => LoadEmbedded("majora_char_88.png");
        internal static SKBitmap majora_char_89 => LoadEmbedded("majora_char_89.png");
        internal static SKBitmap majora_char_8a => LoadEmbedded("majora_char_8a.png");
        internal static SKBitmap majora_char_8b => LoadEmbedded("majora_char_8b.png");
        internal static SKBitmap majora_char_8c => LoadEmbedded("majora_char_8c.png");
        internal static SKBitmap majora_char_8d => LoadEmbedded("majora_char_8d.png");
        internal static SKBitmap majora_char_8e => LoadEmbedded("majora_char_8e.png");
        internal static SKBitmap majora_char_8f => LoadEmbedded("majora_char_8f.png");
        internal static SKBitmap majora_char_90 => LoadEmbedded("majora_char_90.png");
        internal static SKBitmap majora_char_91 => LoadEmbedded("majora_char_91.png");
        internal static SKBitmap majora_char_92 => LoadEmbedded("majora_char_92.png");
        internal static SKBitmap majora_char_93 => LoadEmbedded("majora_char_93.png");
        internal static SKBitmap majora_char_94 => LoadEmbedded("majora_char_94.png");
        internal static SKBitmap majora_char_95 => LoadEmbedded("majora_char_95.png");
        internal static SKBitmap majora_char_96 => LoadEmbedded("majora_char_96.png");
        internal static SKBitmap majora_char_97 => LoadEmbedded("majora_char_97.png");
        internal static SKBitmap majora_char_98 => LoadEmbedded("majora_char_98.png");
        internal static SKBitmap majora_char_99 => LoadEmbedded("majora_char_99.png");
        internal static SKBitmap majora_char_9a => LoadEmbedded("majora_char_9a.png");
        internal static SKBitmap majora_char_9b => LoadEmbedded("majora_char_9b.png");
        internal static SKBitmap majora_char_9c => LoadEmbedded("majora_char_9c.png");
        internal static SKBitmap majora_char_9d => LoadEmbedded("majora_char_9d.png");
        internal static SKBitmap majora_char_9e => LoadEmbedded("majora_char_9e.png");
        internal static SKBitmap majora_char_9f => LoadEmbedded("majora_char_9f.png");
        internal static SKBitmap majora_char_a0 => LoadEmbedded("majora_char_a0.png");
        internal static SKBitmap majora_char_a1 => LoadEmbedded("majora_char_a1.png");
        internal static SKBitmap majora_char_a2 => LoadEmbedded("majora_char_a2.png");
        internal static SKBitmap majora_char_a3 => LoadEmbedded("majora_char_a3.png");
        internal static SKBitmap majora_char_a4 => LoadEmbedded("majora_char_a4.png");
        internal static SKBitmap majora_char_a5 => LoadEmbedded("majora_char_a5.png");
        internal static SKBitmap majora_char_a6 => LoadEmbedded("majora_char_a6.png");
        internal static SKBitmap majora_char_a7 => LoadEmbedded("majora_char_a7.png");
        internal static SKBitmap majora_char_a8 => LoadEmbedded("majora_char_a8.png");
        internal static SKBitmap majora_char_a9 => LoadEmbedded("majora_char_a9.png");
        internal static SKBitmap majora_char_aa => LoadEmbedded("majora_char_aa.png");
        internal static SKBitmap majora_char_ab => LoadEmbedded("majora_char_ab.png");
        internal static SKBitmap majora_char_ac => LoadEmbedded("majora_char_ac.png");
        internal static SKBitmap majora_char_ad => LoadEmbedded("majora_char_ad.png");
        internal static SKBitmap majora_char_ae => LoadEmbedded("majora_char_ae.png");
        internal static SKBitmap majora_char_af => LoadEmbedded("majora_char_af.png");
        internal static SKBitmap majora_char_b0 => LoadEmbedded("majora_char_b0.png");
        internal static SKBitmap majora_char_b1 => LoadEmbedded("majora_char_b1.png");
        internal static SKBitmap majora_char_b2 => LoadEmbedded("majora_char_b2.png");
        internal static SKBitmap majora_char_b3 => LoadEmbedded("majora_char_b3.png");
        internal static SKBitmap majora_char_b4 => LoadEmbedded("majora_char_b4.png");
        internal static SKBitmap majora_char_b5 => LoadEmbedded("majora_char_b5.png");
        internal static SKBitmap majora_char_b6 => LoadEmbedded("majora_char_b6.png");
        internal static SKBitmap majora_char_b7 => LoadEmbedded("majora_char_b7.png");
        internal static SKBitmap majora_char_b8 => LoadEmbedded("majora_char_b8.png");
        internal static SKBitmap majora_char_b9 => LoadEmbedded("majora_char_b9.png");
        internal static SKBitmap majora_char_ba => LoadEmbedded("majora_char_ba.png");
        internal static SKBitmap majora_char_bb => LoadEmbedded("majora_char_bb.png");
        internal static SKBitmap majora_Fading_Box => LoadEmbedded("majora_Fading_Box.png");
        internal static SKBitmap majora_icon_1 => LoadEmbedded("majora_icon_1.png");
        internal static SKBitmap majora_icon_10 => LoadEmbedded("majora_icon_10.png");
        internal static SKBitmap majora_icon_100 => LoadEmbedded("majora_icon_100.png");
        internal static SKBitmap majora_icon_101 => LoadEmbedded("majora_icon_101.png");
        internal static SKBitmap majora_icon_102 => LoadEmbedded("majora_icon_102.png");
        internal static SKBitmap majora_icon_103 => LoadEmbedded("majora_icon_103.png");
        internal static SKBitmap majora_icon_104 => LoadEmbedded("majora_icon_104.png");
        internal static SKBitmap majora_icon_105 => LoadEmbedded("majora_icon_105.png");
        internal static SKBitmap majora_icon_106 => LoadEmbedded("majora_icon_106.png");
        internal static SKBitmap majora_icon_107 => LoadEmbedded("majora_icon_107.png");
        internal static SKBitmap majora_icon_11 => LoadEmbedded("majora_icon_11.png");
        internal static SKBitmap majora_icon_110 => LoadEmbedded("majora_icon_110.png");
        internal static SKBitmap majora_icon_111 => LoadEmbedded("majora_icon_111.png");
        internal static SKBitmap majora_icon_112 => LoadEmbedded("majora_icon_112.png");
        internal static SKBitmap majora_icon_114 => LoadEmbedded("majora_icon_114.png");
        internal static SKBitmap majora_icon_12 => LoadEmbedded("majora_icon_12.png");
        internal static SKBitmap majora_icon_120 => LoadEmbedded("majora_icon_120.png");
        internal static SKBitmap majora_icon_121 => LoadEmbedded("majora_icon_121.png");
        internal static SKBitmap majora_icon_122 => LoadEmbedded("majora_icon_122.png");
        internal static SKBitmap majora_icon_123 => LoadEmbedded("majora_icon_123.png");
        internal static SKBitmap majora_icon_124 => LoadEmbedded("majora_icon_124.png");
        internal static SKBitmap majora_icon_125 => LoadEmbedded("majora_icon_125.png");
        internal static SKBitmap majora_icon_126 => LoadEmbedded("majora_icon_126.png");
        internal static SKBitmap majora_icon_127 => LoadEmbedded("majora_icon_127.png");
        internal static SKBitmap majora_icon_128 => LoadEmbedded("majora_icon_128.png");
        internal static SKBitmap majora_icon_129 => LoadEmbedded("majora_icon_129.png");
        internal static SKBitmap majora_icon_13 => LoadEmbedded("majora_icon_13.png");
        internal static SKBitmap majora_icon_130 => LoadEmbedded("majora_icon_130.png");
        internal static SKBitmap majora_icon_131 => LoadEmbedded("majora_icon_131.png");
        internal static SKBitmap majora_icon_132 => LoadEmbedded("majora_icon_132.png");
        internal static SKBitmap majora_icon_133 => LoadEmbedded("majora_icon_133.png");
        internal static SKBitmap majora_icon_134 => LoadEmbedded("majora_icon_134.png");
        internal static SKBitmap majora_icon_135 => LoadEmbedded("majora_icon_135.png");
        internal static SKBitmap majora_icon_136 => LoadEmbedded("majora_icon_136.png");
        internal static SKBitmap majora_icon_137 => LoadEmbedded("majora_icon_137.png");
        internal static SKBitmap majora_icon_138 => LoadEmbedded("majora_icon_138.png");
        internal static SKBitmap majora_icon_139 => LoadEmbedded("majora_icon_139.png");
        internal static SKBitmap majora_icon_14 => LoadEmbedded("majora_icon_14.png");
        internal static SKBitmap majora_icon_140 => LoadEmbedded("majora_icon_140.png");
        internal static SKBitmap majora_icon_141 => LoadEmbedded("majora_icon_141.png");
        internal static SKBitmap majora_icon_142 => LoadEmbedded("majora_icon_142.png");
        internal static SKBitmap majora_icon_143 => LoadEmbedded("majora_icon_143.png");
        internal static SKBitmap majora_icon_145 => LoadEmbedded("majora_icon_145.png");
        internal static SKBitmap majora_icon_147 => LoadEmbedded("majora_icon_147.png");
        internal static SKBitmap majora_icon_148 => LoadEmbedded("majora_icon_148.png");
        internal static SKBitmap majora_icon_149 => LoadEmbedded("majora_icon_149.png");
        internal static SKBitmap majora_icon_15 => LoadEmbedded("majora_icon_15.png");
        internal static SKBitmap majora_icon_150 => LoadEmbedded("majora_icon_150.png");
        internal static SKBitmap majora_icon_151 => LoadEmbedded("majora_icon_151.png");
        internal static SKBitmap majora_icon_152 => LoadEmbedded("majora_icon_152.png");
        internal static SKBitmap majora_icon_153 => LoadEmbedded("majora_icon_153.png");
        internal static SKBitmap majora_icon_154 => LoadEmbedded("majora_icon_154.png");
        internal static SKBitmap majora_icon_16 => LoadEmbedded("majora_icon_16.png");
        internal static SKBitmap majora_icon_160 => LoadEmbedded("majora_icon_160.png");
        internal static SKBitmap majora_icon_161 => LoadEmbedded("majora_icon_161.png");
        internal static SKBitmap majora_icon_17 => LoadEmbedded("majora_icon_17.png");
        internal static SKBitmap majora_icon_170 => LoadEmbedded("majora_icon_170.png");
        internal static SKBitmap majora_icon_171 => LoadEmbedded("majora_icon_171.png");
        internal static SKBitmap majora_icon_179 => LoadEmbedded("majora_icon_179.png");
        internal static SKBitmap majora_icon_18 => LoadEmbedded("majora_icon_18.png");
        internal static SKBitmap majora_icon_180 => LoadEmbedded("majora_icon_180.png");
        internal static SKBitmap majora_icon_181 => LoadEmbedded("majora_icon_181.png");
        internal static SKBitmap majora_icon_182 => LoadEmbedded("majora_icon_182.png");
        internal static SKBitmap majora_icon_183 => LoadEmbedded("majora_icon_183.png");
        internal static SKBitmap majora_icon_184 => LoadEmbedded("majora_icon_184.png");
        internal static SKBitmap majora_icon_185 => LoadEmbedded("majora_icon_185.png");
        internal static SKBitmap majora_icon_19 => LoadEmbedded("majora_icon_19.png");
        internal static SKBitmap majora_icon_2 => LoadEmbedded("majora_icon_2.png");
        internal static SKBitmap majora_icon_20 => LoadEmbedded("majora_icon_20.png");
        internal static SKBitmap majora_icon_21 => LoadEmbedded("majora_icon_21.png");
        internal static SKBitmap majora_icon_22 => LoadEmbedded("majora_icon_22.png");
        internal static SKBitmap majora_icon_220 => LoadEmbedded("majora_icon_220.png");
        internal static SKBitmap majora_icon_221 => LoadEmbedded("majora_icon_221.png");
        internal static SKBitmap majora_icon_222 => LoadEmbedded("majora_icon_222.png");
        internal static SKBitmap majora_icon_223 => LoadEmbedded("majora_icon_223.png");
        internal static SKBitmap majora_icon_224 => LoadEmbedded("majora_icon_224.png");
        internal static SKBitmap majora_icon_225 => LoadEmbedded("majora_icon_225.png");
        internal static SKBitmap majora_icon_226 => LoadEmbedded("majora_icon_226.png");
        internal static SKBitmap majora_icon_227 => LoadEmbedded("majora_icon_227.png");
        internal static SKBitmap majora_icon_228 => LoadEmbedded("majora_icon_228.png");
        internal static SKBitmap majora_icon_229 => LoadEmbedded("majora_icon_229.png");
        internal static SKBitmap majora_icon_23 => LoadEmbedded("majora_icon_23.png");
        internal static SKBitmap majora_icon_230 => LoadEmbedded("majora_icon_230.png");
        internal static SKBitmap majora_icon_231 => LoadEmbedded("majora_icon_231.png");
        internal static SKBitmap majora_icon_232 => LoadEmbedded("majora_icon_232.png");
        internal static SKBitmap majora_icon_233 => LoadEmbedded("majora_icon_233.png");
        internal static SKBitmap majora_icon_234 => LoadEmbedded("majora_icon_234.png");
        internal static SKBitmap majora_icon_235 => LoadEmbedded("majora_icon_235.png");
        internal static SKBitmap majora_icon_236 => LoadEmbedded("majora_icon_236.png");
        internal static SKBitmap majora_icon_237 => LoadEmbedded("majora_icon_237.png");
        internal static SKBitmap majora_icon_238 => LoadEmbedded("majora_icon_238.png");
        internal static SKBitmap majora_icon_239 => LoadEmbedded("majora_icon_239.png");
        internal static SKBitmap majora_icon_24 => LoadEmbedded("majora_icon_24.png");
        internal static SKBitmap majora_icon_240 => LoadEmbedded("majora_icon_240.png");
        internal static SKBitmap majora_icon_25 => LoadEmbedded("majora_icon_25.png");
        internal static SKBitmap majora_icon_26 => LoadEmbedded("majora_icon_26.png");
        internal static SKBitmap majora_icon_27 => LoadEmbedded("majora_icon_27.png");
        internal static SKBitmap majora_icon_28 => LoadEmbedded("majora_icon_28.png");
        internal static SKBitmap majora_icon_29 => LoadEmbedded("majora_icon_29.png");
        internal static SKBitmap majora_icon_3 => LoadEmbedded("majora_icon_3.png");
        internal static SKBitmap majora_icon_30 => LoadEmbedded("majora_icon_30.png");
        internal static SKBitmap majora_icon_301 => LoadEmbedded("majora_icon_301.png");
        internal static SKBitmap majora_icon_302 => LoadEmbedded("majora_icon_302.png");
        internal static SKBitmap majora_icon_303 => LoadEmbedded("majora_icon_303.png");
        internal static SKBitmap majora_icon_31 => LoadEmbedded("majora_icon_31.png");
        internal static SKBitmap majora_icon_32 => LoadEmbedded("majora_icon_32.png");
        internal static SKBitmap majora_icon_33 => LoadEmbedded("majora_icon_33.png");
        internal static SKBitmap majora_icon_34 => LoadEmbedded("majora_icon_34.png");
        internal static SKBitmap majora_icon_35 => LoadEmbedded("majora_icon_35.png");
        internal static SKBitmap majora_icon_36 => LoadEmbedded("majora_icon_36.png");
        internal static SKBitmap majora_icon_37 => LoadEmbedded("majora_icon_37.png");
        internal static SKBitmap majora_icon_38 => LoadEmbedded("majora_icon_38.png");
        internal static SKBitmap majora_icon_39 => LoadEmbedded("majora_icon_39.png");
        internal static SKBitmap majora_icon_4 => LoadEmbedded("majora_icon_4.png");
        internal static SKBitmap majora_icon_40 => LoadEmbedded("majora_icon_40.png");
        internal static SKBitmap majora_icon_41 => LoadEmbedded("majora_icon_41.png");
        internal static SKBitmap majora_icon_42 => LoadEmbedded("majora_icon_42.png");
        internal static SKBitmap majora_icon_5 => LoadEmbedded("majora_icon_5.png");
        internal static SKBitmap majora_icon_50 => LoadEmbedded("majora_icon_50.png");
        internal static SKBitmap majora_icon_51 => LoadEmbedded("majora_icon_51.png");
        internal static SKBitmap majora_icon_52 => LoadEmbedded("majora_icon_52.png");
        internal static SKBitmap majora_icon_53 => LoadEmbedded("majora_icon_53.png");
        internal static SKBitmap majora_icon_54 => LoadEmbedded("majora_icon_54.png");
        internal static SKBitmap majora_icon_55 => LoadEmbedded("majora_icon_55.png");
        internal static SKBitmap majora_icon_56 => LoadEmbedded("majora_icon_56.png");
        internal static SKBitmap majora_icon_57 => LoadEmbedded("majora_icon_57.png");
        internal static SKBitmap majora_icon_58 => LoadEmbedded("majora_icon_58.png");
        internal static SKBitmap majora_icon_59 => LoadEmbedded("majora_icon_59.png");
        internal static SKBitmap majora_icon_6 => LoadEmbedded("majora_icon_6.png");
        internal static SKBitmap majora_icon_60 => LoadEmbedded("majora_icon_60.png");
        internal static SKBitmap majora_icon_61 => LoadEmbedded("majora_icon_61.png");
        internal static SKBitmap majora_icon_62 => LoadEmbedded("majora_icon_62.png");
        internal static SKBitmap majora_icon_63 => LoadEmbedded("majora_icon_63.png");
        internal static SKBitmap majora_icon_64 => LoadEmbedded("majora_icon_64.png");
        internal static SKBitmap majora_icon_65 => LoadEmbedded("majora_icon_65.png");
        internal static SKBitmap majora_icon_66 => LoadEmbedded("majora_icon_66.png");
        internal static SKBitmap majora_icon_67 => LoadEmbedded("majora_icon_67.png");
        internal static SKBitmap majora_icon_68 => LoadEmbedded("majora_icon_68.png");
        internal static SKBitmap majora_icon_7 => LoadEmbedded("majora_icon_7.png");
        internal static SKBitmap majora_icon_76 => LoadEmbedded("majora_icon_76.png");
        internal static SKBitmap majora_icon_8 => LoadEmbedded("majora_icon_8.png");
        internal static SKBitmap majora_icon_80 => LoadEmbedded("majora_icon_80.png");
        internal static SKBitmap majora_icon_82 => LoadEmbedded("majora_icon_82.png");
        internal static SKBitmap majora_icon_85 => LoadEmbedded("majora_icon_85.png");
        internal static SKBitmap majora_icon_86 => LoadEmbedded("majora_icon_86.png");
        internal static SKBitmap majora_icon_87 => LoadEmbedded("majora_icon_87.png");
        internal static SKBitmap majora_icon_88 => LoadEmbedded("majora_icon_88.png");
        internal static SKBitmap majora_icon_89 => LoadEmbedded("majora_icon_89.png");
        internal static SKBitmap majora_icon_9 => LoadEmbedded("majora_icon_9.png");
        internal static SKBitmap majora_icon_90 => LoadEmbedded("majora_icon_90.png");
        internal static SKBitmap majora_icon_91 => LoadEmbedded("majora_icon_91.png");
        internal static SKBitmap majora_icon_92 => LoadEmbedded("majora_icon_92.png");
        internal static SKBitmap majora_icon_93 => LoadEmbedded("majora_icon_93.png");
        internal static SKBitmap majora_icon_94 => LoadEmbedded("majora_icon_94.png");
        internal static SKBitmap majora_icon_95 => LoadEmbedded("majora_icon_95.png");
        internal static SKBitmap majora_icon_96 => LoadEmbedded("majora_icon_96.png");
        internal static SKBitmap majora_icon_97 => LoadEmbedded("majora_icon_97.png");
        internal static SKBitmap majora_icon_98 => LoadEmbedded("majora_icon_98.png");
        internal static SKBitmap majora_icon_99 => LoadEmbedded("majora_icon_99.png");
        internal static SKBitmap majora_xmes_left => LoadEmbedded("majora_xmes_left.png");
        internal static SKBitmap majora_xmes_right => LoadEmbedded("majora_xmes_right.png");
        internal static SKBitmap xmes_left => LoadEmbedded("xmes_left.png");
        internal static SKBitmap xmes_right => LoadEmbedded("xmes_right.png");

        // Case-insensitive lookup by logical name (without extension), for call sites
        // that need to build the resource name dynamically at runtime rather than
        // referencing a fixed property. Returns null instead of throwing if not found.
        private static readonly System.Collections.Generic.Dictionary<string, string> NameLookup =
            new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase)
            {
                { "Box_Arrow", "Box_Arrow.png" },
                { "Box_Blue", "Box_Blue.png" },
                { "Box_Default", "Box_Default.png" },
                { "Box_End", "Box_End.png" },
                { "Box_Staff", "Box_Staff.png" },
                { "Box_Triangle", "Box_Triangle.png" },
                { "Box_Wooden", "Box_Wooden.png" },
                { "char_20", "char_20.png" },
                { "char_21", "char_21.png" },
                { "char_22", "char_22.png" },
                { "char_23", "char_23.png" },
                { "char_24", "char_24.png" },
                { "char_25", "char_25.png" },
                { "char_26", "char_26.png" },
                { "char_27", "char_27.png" },
                { "char_28", "char_28.png" },
                { "char_29", "char_29.png" },
                { "char_2a", "char_2a.png" },
                { "char_2b", "char_2b.png" },
                { "char_2c", "char_2c.png" },
                { "char_2d", "char_2d.png" },
                { "char_2e", "char_2e.png" },
                { "char_2f", "char_2f.png" },
                { "char_30", "char_30.png" },
                { "char_31", "char_31.png" },
                { "char_32", "char_32.png" },
                { "char_33", "char_33.png" },
                { "char_34", "char_34.png" },
                { "char_35", "char_35.png" },
                { "char_36", "char_36.png" },
                { "char_37", "char_37.png" },
                { "char_38", "char_38.png" },
                { "char_39", "char_39.png" },
                { "char_3a", "char_3a.png" },
                { "char_3b", "char_3b.png" },
                { "char_3c", "char_3c.png" },
                { "char_3d", "char_3d.png" },
                { "char_3e", "char_3e.png" },
                { "char_3f", "char_3f.png" },
                { "char_40", "char_40.png" },
                { "char_41", "char_41.png" },
                { "char_42", "char_42.png" },
                { "char_43", "char_43.png" },
                { "char_44", "char_44.png" },
                { "char_45", "char_45.png" },
                { "char_46", "char_46.png" },
                { "char_47", "char_47.png" },
                { "char_48", "char_48.png" },
                { "char_49", "char_49.png" },
                { "char_4a", "char_4a.png" },
                { "char_4b", "char_4b.png" },
                { "char_4c", "char_4c.png" },
                { "char_4d", "char_4d.png" },
                { "char_4e", "char_4e.png" },
                { "char_4f", "char_4f.png" },
                { "char_50", "char_50.png" },
                { "char_51", "char_51.png" },
                { "char_52", "char_52.png" },
                { "char_53", "char_53.png" },
                { "char_54", "char_54.png" },
                { "char_55", "char_55.png" },
                { "char_56", "char_56.png" },
                { "char_57", "char_57.png" },
                { "char_58", "char_58.png" },
                { "char_59", "char_59.png" },
                { "char_5a", "char_5a.png" },
                { "char_5b", "char_5b.png" },
                { "char_5c", "char_5c.png" },
                { "char_5d", "char_5d.png" },
                { "char_5e", "char_5e.png" },
                { "char_5f", "char_5f.png" },
                { "char_60", "char_60.png" },
                { "char_61", "char_61.png" },
                { "char_62", "char_62.png" },
                { "char_63", "char_63.png" },
                { "char_64", "char_64.png" },
                { "char_65", "char_65.png" },
                { "char_66", "char_66.png" },
                { "char_67", "char_67.png" },
                { "char_68", "char_68.png" },
                { "char_69", "char_69.png" },
                { "char_6a", "char_6a.png" },
                { "char_6b", "char_6b.png" },
                { "char_6c", "char_6c.png" },
                { "char_6d", "char_6d.png" },
                { "char_6e", "char_6e.png" },
                { "char_6f", "char_6f.png" },
                { "char_70", "char_70.png" },
                { "char_71", "char_71.png" },
                { "char_72", "char_72.png" },
                { "char_73", "char_73.png" },
                { "char_74", "char_74.png" },
                { "char_75", "char_75.png" },
                { "char_76", "char_76.png" },
                { "char_77", "char_77.png" },
                { "char_78", "char_78.png" },
                { "char_79", "char_79.png" },
                { "char_7a", "char_7a.png" },
                { "char_7b", "char_7b.png" },
                { "char_7c", "char_7c.png" },
                { "char_7d", "char_7d.png" },
                { "char_7e", "char_7e.png" },
                { "char_7f", "char_7f.png" },
                { "char_80", "char_80.png" },
                { "char_81", "char_81.png" },
                { "char_82", "char_82.png" },
                { "char_83", "char_83.png" },
                { "char_84", "char_84.png" },
                { "char_85", "char_85.png" },
                { "char_86", "char_86.png" },
                { "char_87", "char_87.png" },
                { "char_88", "char_88.png" },
                { "char_89", "char_89.png" },
                { "char_8a", "char_8a.png" },
                { "char_8b", "char_8b.png" },
                { "char_8c", "char_8c.png" },
                { "char_8d", "char_8d.png" },
                { "char_8e", "char_8e.png" },
                { "char_8f", "char_8f.png" },
                { "char_90", "char_90.png" },
                { "char_91", "char_91.png" },
                { "char_92", "char_92.png" },
                { "char_93", "char_93.png" },
                { "char_94", "char_94.png" },
                { "char_95", "char_95.png" },
                { "char_96", "char_96.png" },
                { "char_97", "char_97.png" },
                { "char_98", "char_98.png" },
                { "char_99", "char_99.png" },
                { "char_9a", "char_9a.png" },
                { "char_9b", "char_9b.png" },
                { "char_9c", "char_9c.png" },
                { "char_9d", "char_9d.png" },
                { "char_9e", "char_9e.png" },
                { "char_9f", "char_9f.png" },
                { "char_a0", "char_a0.png" },
                { "char_a1", "char_a1.png" },
                { "char_a2", "char_a2.png" },
                { "char_a3", "char_a3.png" },
                { "char_a4", "char_a4.png" },
                { "char_a5", "char_a5.png" },
                { "char_a6", "char_a6.png" },
                { "char_a7", "char_a7.png" },
                { "char_a8", "char_a8.png" },
                { "char_a9", "char_a9.png" },
                { "char_aa", "char_aa.png" },
                { "char_ab", "char_ab.png" },
                { "Fading_Box", "Fading_Box.png" },
                { "Fading_Box1", "Fading_Box1.png" },
                { "icon_0", "icon_0.png" },
                { "icon_1", "icon_1.png" },
                { "icon_10", "icon_10.png" },
                { "icon_102", "icon_102.png" },
                { "icon_103", "icon_103.png" },
                { "icon_104", "icon_104.png" },
                { "icon_105", "icon_105.png" },
                { "icon_106", "icon_106.png" },
                { "icon_107", "icon_107.png" },
                { "icon_108", "icon_108.png" },
                { "icon_109", "icon_109.png" },
                { "icon_11", "icon_11.png" },
                { "icon_110", "icon_110.png" },
                { "icon_111", "icon_111.png" },
                { "icon_112", "icon_112.png" },
                { "icon_113", "icon_113.png" },
                { "icon_114", "icon_114.png" },
                { "icon_115", "icon_115.png" },
                { "icon_116", "icon_116.png" },
                { "icon_117", "icon_117.png" },
                { "icon_118", "icon_118.png" },
                { "icon_119", "icon_119.png" },
                { "icon_12", "icon_12.png" },
                { "icon_120", "icon_120.png" },
                { "icon_121", "icon_121.png" },
                { "icon_13", "icon_13.png" },
                { "icon_14", "icon_14.png" },
                { "icon_15", "icon_15.png" },
                { "icon_16", "icon_16.png" },
                { "icon_17", "icon_17.png" },
                { "icon_18", "icon_18.png" },
                { "icon_19", "icon_19.png" },
                { "icon_2", "icon_2.png" },
                { "icon_20", "icon_20.png" },
                { "icon_21", "icon_21.png" },
                { "icon_22", "icon_22.png" },
                { "icon_23", "icon_23.png" },
                { "icon_24", "icon_24.png" },
                { "icon_25", "icon_25.png" },
                { "icon_26", "icon_26.png" },
                { "icon_27", "icon_27.png" },
                { "icon_28", "icon_28.png" },
                { "icon_29", "icon_29.png" },
                { "icon_3", "icon_3.png" },
                { "icon_30", "icon_30.png" },
                { "icon_31", "icon_31.png" },
                { "icon_32", "icon_32.png" },
                { "icon_33", "icon_33.png" },
                { "icon_34", "icon_34.png" },
                { "icon_35", "icon_35.png" },
                { "icon_36", "icon_36.png" },
                { "icon_37", "icon_37.png" },
                { "icon_38", "icon_38.png" },
                { "icon_39", "icon_39.png" },
                { "icon_4", "icon_4.png" },
                { "icon_40", "icon_40.png" },
                { "icon_41", "icon_41.png" },
                { "icon_42", "icon_42.png" },
                { "icon_43", "icon_43.png" },
                { "icon_44", "icon_44.png" },
                { "icon_45", "icon_45.png" },
                { "icon_46", "icon_46.png" },
                { "icon_47", "icon_47.png" },
                { "icon_48", "icon_48.png" },
                { "icon_49", "icon_49.png" },
                { "icon_5", "icon_5.png" },
                { "icon_50", "icon_50.png" },
                { "icon_51", "icon_51.png" },
                { "icon_52", "icon_52.png" },
                { "icon_53", "icon_53.png" },
                { "icon_54", "icon_54.png" },
                { "icon_55", "icon_55.png" },
                { "icon_56", "icon_56.png" },
                { "icon_57", "icon_57.png" },
                { "icon_58", "icon_58.png" },
                { "icon_59", "icon_59.png" },
                { "icon_6", "icon_6.png" },
                { "icon_60", "icon_60.png" },
                { "icon_61", "icon_61.png" },
                { "icon_62", "icon_62.png" },
                { "icon_63", "icon_63.png" },
                { "icon_64", "icon_64.png" },
                { "icon_65", "icon_65.png" },
                { "icon_66", "icon_66.png" },
                { "icon_67", "icon_67.png" },
                { "icon_68", "icon_68.png" },
                { "icon_69", "icon_69.png" },
                { "icon_7", "icon_7.png" },
                { "icon_70", "icon_70.png" },
                { "icon_71", "icon_71.png" },
                { "icon_72", "icon_72.png" },
                { "icon_73", "icon_73.png" },
                { "icon_74", "icon_74.png" },
                { "icon_75", "icon_75.png" },
                { "icon_76", "icon_76.png" },
                { "icon_77", "icon_77.png" },
                { "icon_78", "icon_78.png" },
                { "icon_79", "icon_79.png" },
                { "icon_8", "icon_8.png" },
                { "icon_80", "icon_80.png" },
                { "icon_81", "icon_81.png" },
                { "icon_82", "icon_82.png" },
                { "icon_83", "icon_83.png" },
                { "icon_84", "icon_84.png" },
                { "icon_85", "icon_85.png" },
                { "icon_86", "icon_86.png" },
                { "icon_87", "icon_87.png" },
                { "icon_88", "icon_88.png" },
                { "icon_89", "icon_89.png" },
                { "icon_9", "icon_9.png" },
                { "majora_Box_Arrow", "majora_Box_Arrow.png" },
                { "majora_Box_Bomber", "majora_Box_Bomber.png" },
                { "majora_Box_Default", "majora_Box_Default.png" },
                { "majora_Box_End", "majora_Box_End.png" },
                { "majora_Box_Staff", "majora_Box_Staff.png" },
                { "majora_Box_Triangle", "majora_Box_Triangle.png" },
                { "majora_Box_Wooden", "majora_Box_Wooden.png" },
                { "majora_char_20", "majora_char_20.png" },
                { "majora_char_21", "majora_char_21.png" },
                { "majora_char_22", "majora_char_22.png" },
                { "majora_char_23", "majora_char_23.png" },
                { "majora_char_24", "majora_char_24.png" },
                { "majora_char_25", "majora_char_25.png" },
                { "majora_char_26", "majora_char_26.png" },
                { "majora_char_27", "majora_char_27.png" },
                { "majora_char_28", "majora_char_28.png" },
                { "majora_char_29", "majora_char_29.png" },
                { "majora_char_2a", "majora_char_2a.png" },
                { "majora_char_2b", "majora_char_2b.png" },
                { "majora_char_2c", "majora_char_2c.png" },
                { "majora_char_2d", "majora_char_2d.png" },
                { "majora_char_2e", "majora_char_2e.png" },
                { "majora_char_2f", "majora_char_2f.png" },
                { "majora_char_30", "majora_char_30.png" },
                { "majora_char_31", "majora_char_31.png" },
                { "majora_char_32", "majora_char_32.png" },
                { "majora_char_33", "majora_char_33.png" },
                { "majora_char_34", "majora_char_34.png" },
                { "majora_char_35", "majora_char_35.png" },
                { "majora_char_36", "majora_char_36.png" },
                { "majora_char_37", "majora_char_37.png" },
                { "majora_char_38", "majora_char_38.png" },
                { "majora_char_39", "majora_char_39.png" },
                { "majora_char_3a", "majora_char_3a.png" },
                { "majora_char_3b", "majora_char_3b.png" },
                { "majora_char_3c", "majora_char_3c.png" },
                { "majora_char_3d", "majora_char_3d.png" },
                { "majora_char_3e", "majora_char_3e.png" },
                { "majora_char_3f", "majora_char_3f.png" },
                { "majora_char_40", "majora_char_40.png" },
                { "majora_char_41", "majora_char_41.png" },
                { "majora_char_42", "majora_char_42.png" },
                { "majora_char_43", "majora_char_43.png" },
                { "majora_char_44", "majora_char_44.png" },
                { "majora_char_45", "majora_char_45.png" },
                { "majora_char_46", "majora_char_46.png" },
                { "majora_char_47", "majora_char_47.png" },
                { "majora_char_48", "majora_char_48.png" },
                { "majora_char_49", "majora_char_49.png" },
                { "majora_char_4a", "majora_char_4a.png" },
                { "majora_char_4b", "majora_char_4b.png" },
                { "majora_char_4c", "majora_char_4c.png" },
                { "majora_char_4d", "majora_char_4d.png" },
                { "majora_char_4e", "majora_char_4e.png" },
                { "majora_char_4f", "majora_char_4f.png" },
                { "majora_char_50", "majora_char_50.png" },
                { "majora_char_51", "majora_char_51.png" },
                { "majora_char_52", "majora_char_52.png" },
                { "majora_char_53", "majora_char_53.png" },
                { "majora_char_54", "majora_char_54.png" },
                { "majora_char_55", "majora_char_55.png" },
                { "majora_char_56", "majora_char_56.png" },
                { "majora_char_57", "majora_char_57.png" },
                { "majora_char_58", "majora_char_58.png" },
                { "majora_char_59", "majora_char_59.png" },
                { "majora_char_5a", "majora_char_5a.png" },
                { "majora_char_5b", "majora_char_5b.png" },
                { "majora_char_5c", "majora_char_5c.png" },
                { "majora_char_5d", "majora_char_5d.png" },
                { "majora_char_5e", "majora_char_5e.png" },
                { "majora_char_5f", "majora_char_5f.png" },
                { "majora_char_60", "majora_char_60.png" },
                { "majora_char_61", "majora_char_61.png" },
                { "majora_char_62", "majora_char_62.png" },
                { "majora_char_63", "majora_char_63.png" },
                { "majora_char_64", "majora_char_64.png" },
                { "majora_char_65", "majora_char_65.png" },
                { "majora_char_66", "majora_char_66.png" },
                { "majora_char_67", "majora_char_67.png" },
                { "majora_char_68", "majora_char_68.png" },
                { "majora_char_69", "majora_char_69.png" },
                { "majora_char_6a", "majora_char_6a.png" },
                { "majora_char_6b", "majora_char_6b.png" },
                { "majora_char_6c", "majora_char_6c.png" },
                { "majora_char_6d", "majora_char_6d.png" },
                { "majora_char_6e", "majora_char_6e.png" },
                { "majora_char_6f", "majora_char_6f.png" },
                { "majora_char_70", "majora_char_70.png" },
                { "majora_char_71", "majora_char_71.png" },
                { "majora_char_72", "majora_char_72.png" },
                { "majora_char_73", "majora_char_73.png" },
                { "majora_char_74", "majora_char_74.png" },
                { "majora_char_75", "majora_char_75.png" },
                { "majora_char_76", "majora_char_76.png" },
                { "majora_char_77", "majora_char_77.png" },
                { "majora_char_78", "majora_char_78.png" },
                { "majora_char_79", "majora_char_79.png" },
                { "majora_char_7a", "majora_char_7a.png" },
                { "majora_char_7b", "majora_char_7b.png" },
                { "majora_char_7c", "majora_char_7c.png" },
                { "majora_char_7d", "majora_char_7d.png" },
                { "majora_char_7e", "majora_char_7e.png" },
                { "majora_char_7f", "majora_char_7f.png" },
                { "majora_char_80", "majora_char_80.png" },
                { "majora_char_81", "majora_char_81.png" },
                { "majora_char_82", "majora_char_82.png" },
                { "majora_char_83", "majora_char_83.png" },
                { "majora_char_84", "majora_char_84.png" },
                { "majora_char_85", "majora_char_85.png" },
                { "majora_char_86", "majora_char_86.png" },
                { "majora_char_87", "majora_char_87.png" },
                { "majora_char_88", "majora_char_88.png" },
                { "majora_char_89", "majora_char_89.png" },
                { "majora_char_8a", "majora_char_8a.png" },
                { "majora_char_8b", "majora_char_8b.png" },
                { "majora_char_8c", "majora_char_8c.png" },
                { "majora_char_8d", "majora_char_8d.png" },
                { "majora_char_8e", "majora_char_8e.png" },
                { "majora_char_8f", "majora_char_8f.png" },
                { "majora_char_90", "majora_char_90.png" },
                { "majora_char_91", "majora_char_91.png" },
                { "majora_char_92", "majora_char_92.png" },
                { "majora_char_93", "majora_char_93.png" },
                { "majora_char_94", "majora_char_94.png" },
                { "majora_char_95", "majora_char_95.png" },
                { "majora_char_96", "majora_char_96.png" },
                { "majora_char_97", "majora_char_97.png" },
                { "majora_char_98", "majora_char_98.png" },
                { "majora_char_99", "majora_char_99.png" },
                { "majora_char_9a", "majora_char_9a.png" },
                { "majora_char_9b", "majora_char_9b.png" },
                { "majora_char_9c", "majora_char_9c.png" },
                { "majora_char_9d", "majora_char_9d.png" },
                { "majora_char_9e", "majora_char_9e.png" },
                { "majora_char_9f", "majora_char_9f.png" },
                { "majora_char_a0", "majora_char_a0.png" },
                { "majora_char_a1", "majora_char_a1.png" },
                { "majora_char_a2", "majora_char_a2.png" },
                { "majora_char_a3", "majora_char_a3.png" },
                { "majora_char_a4", "majora_char_a4.png" },
                { "majora_char_a5", "majora_char_a5.png" },
                { "majora_char_a6", "majora_char_a6.png" },
                { "majora_char_a7", "majora_char_a7.png" },
                { "majora_char_a8", "majora_char_a8.png" },
                { "majora_char_a9", "majora_char_a9.png" },
                { "majora_char_aa", "majora_char_aa.png" },
                { "majora_char_ab", "majora_char_ab.png" },
                { "majora_char_ac", "majora_char_ac.png" },
                { "majora_char_ad", "majora_char_ad.png" },
                { "majora_char_ae", "majora_char_ae.png" },
                { "majora_char_af", "majora_char_af.png" },
                { "majora_char_b0", "majora_char_b0.png" },
                { "majora_char_b1", "majora_char_b1.png" },
                { "majora_char_b2", "majora_char_b2.png" },
                { "majora_char_b3", "majora_char_b3.png" },
                { "majora_char_b4", "majora_char_b4.png" },
                { "majora_char_b5", "majora_char_b5.png" },
                { "majora_char_b6", "majora_char_b6.png" },
                { "majora_char_b7", "majora_char_b7.png" },
                { "majora_char_b8", "majora_char_b8.png" },
                { "majora_char_b9", "majora_char_b9.png" },
                { "majora_char_ba", "majora_char_ba.png" },
                { "majora_char_bb", "majora_char_bb.png" },
                { "majora_Fading_Box", "majora_Fading_Box.png" },
                { "majora_icon_1", "majora_icon_1.png" },
                { "majora_icon_10", "majora_icon_10.png" },
                { "majora_icon_100", "majora_icon_100.png" },
                { "majora_icon_101", "majora_icon_101.png" },
                { "majora_icon_102", "majora_icon_102.png" },
                { "majora_icon_103", "majora_icon_103.png" },
                { "majora_icon_104", "majora_icon_104.png" },
                { "majora_icon_105", "majora_icon_105.png" },
                { "majora_icon_106", "majora_icon_106.png" },
                { "majora_icon_107", "majora_icon_107.png" },
                { "majora_icon_11", "majora_icon_11.png" },
                { "majora_icon_110", "majora_icon_110.png" },
                { "majora_icon_111", "majora_icon_111.png" },
                { "majora_icon_112", "majora_icon_112.png" },
                { "majora_icon_114", "majora_icon_114.png" },
                { "majora_icon_12", "majora_icon_12.png" },
                { "majora_icon_120", "majora_icon_120.png" },
                { "majora_icon_121", "majora_icon_121.png" },
                { "majora_icon_122", "majora_icon_122.png" },
                { "majora_icon_123", "majora_icon_123.png" },
                { "majora_icon_124", "majora_icon_124.png" },
                { "majora_icon_125", "majora_icon_125.png" },
                { "majora_icon_126", "majora_icon_126.png" },
                { "majora_icon_127", "majora_icon_127.png" },
                { "majora_icon_128", "majora_icon_128.png" },
                { "majora_icon_129", "majora_icon_129.png" },
                { "majora_icon_13", "majora_icon_13.png" },
                { "majora_icon_130", "majora_icon_130.png" },
                { "majora_icon_131", "majora_icon_131.png" },
                { "majora_icon_132", "majora_icon_132.png" },
                { "majora_icon_133", "majora_icon_133.png" },
                { "majora_icon_134", "majora_icon_134.png" },
                { "majora_icon_135", "majora_icon_135.png" },
                { "majora_icon_136", "majora_icon_136.png" },
                { "majora_icon_137", "majora_icon_137.png" },
                { "majora_icon_138", "majora_icon_138.png" },
                { "majora_icon_139", "majora_icon_139.png" },
                { "majora_icon_14", "majora_icon_14.png" },
                { "majora_icon_140", "majora_icon_140.png" },
                { "majora_icon_141", "majora_icon_141.png" },
                { "majora_icon_142", "majora_icon_142.png" },
                { "majora_icon_143", "majora_icon_143.png" },
                { "majora_icon_145", "majora_icon_145.png" },
                { "majora_icon_147", "majora_icon_147.png" },
                { "majora_icon_148", "majora_icon_148.png" },
                { "majora_icon_149", "majora_icon_149.png" },
                { "majora_icon_15", "majora_icon_15.png" },
                { "majora_icon_150", "majora_icon_150.png" },
                { "majora_icon_151", "majora_icon_151.png" },
                { "majora_icon_152", "majora_icon_152.png" },
                { "majora_icon_153", "majora_icon_153.png" },
                { "majora_icon_154", "majora_icon_154.png" },
                { "majora_icon_16", "majora_icon_16.png" },
                { "majora_icon_160", "majora_icon_160.png" },
                { "majora_icon_161", "majora_icon_161.png" },
                { "majora_icon_17", "majora_icon_17.png" },
                { "majora_icon_170", "majora_icon_170.png" },
                { "majora_icon_171", "majora_icon_171.png" },
                { "majora_icon_179", "majora_icon_179.png" },
                { "majora_icon_18", "majora_icon_18.png" },
                { "majora_icon_180", "majora_icon_180.png" },
                { "majora_icon_181", "majora_icon_181.png" },
                { "majora_icon_182", "majora_icon_182.png" },
                { "majora_icon_183", "majora_icon_183.png" },
                { "majora_icon_184", "majora_icon_184.png" },
                { "majora_icon_185", "majora_icon_185.png" },
                { "majora_icon_19", "majora_icon_19.png" },
                { "majora_icon_2", "majora_icon_2.png" },
                { "majora_icon_20", "majora_icon_20.png" },
                { "majora_icon_21", "majora_icon_21.png" },
                { "majora_icon_22", "majora_icon_22.png" },
                { "majora_icon_220", "majora_icon_220.png" },
                { "majora_icon_221", "majora_icon_221.png" },
                { "majora_icon_222", "majora_icon_222.png" },
                { "majora_icon_223", "majora_icon_223.png" },
                { "majora_icon_224", "majora_icon_224.png" },
                { "majora_icon_225", "majora_icon_225.png" },
                { "majora_icon_226", "majora_icon_226.png" },
                { "majora_icon_227", "majora_icon_227.png" },
                { "majora_icon_228", "majora_icon_228.png" },
                { "majora_icon_229", "majora_icon_229.png" },
                { "majora_icon_23", "majora_icon_23.png" },
                { "majora_icon_230", "majora_icon_230.png" },
                { "majora_icon_231", "majora_icon_231.png" },
                { "majora_icon_232", "majora_icon_232.png" },
                { "majora_icon_233", "majora_icon_233.png" },
                { "majora_icon_234", "majora_icon_234.png" },
                { "majora_icon_235", "majora_icon_235.png" },
                { "majora_icon_236", "majora_icon_236.png" },
                { "majora_icon_237", "majora_icon_237.png" },
                { "majora_icon_238", "majora_icon_238.png" },
                { "majora_icon_239", "majora_icon_239.png" },
                { "majora_icon_24", "majora_icon_24.png" },
                { "majora_icon_240", "majora_icon_240.png" },
                { "majora_icon_25", "majora_icon_25.png" },
                { "majora_icon_26", "majora_icon_26.png" },
                { "majora_icon_27", "majora_icon_27.png" },
                { "majora_icon_28", "majora_icon_28.png" },
                { "majora_icon_29", "majora_icon_29.png" },
                { "majora_icon_3", "majora_icon_3.png" },
                { "majora_icon_30", "majora_icon_30.png" },
                { "majora_icon_301", "majora_icon_301.png" },
                { "majora_icon_302", "majora_icon_302.png" },
                { "majora_icon_303", "majora_icon_303.png" },
                { "majora_icon_31", "majora_icon_31.png" },
                { "majora_icon_32", "majora_icon_32.png" },
                { "majora_icon_33", "majora_icon_33.png" },
                { "majora_icon_34", "majora_icon_34.png" },
                { "majora_icon_35", "majora_icon_35.png" },
                { "majora_icon_36", "majora_icon_36.png" },
                { "majora_icon_37", "majora_icon_37.png" },
                { "majora_icon_38", "majora_icon_38.png" },
                { "majora_icon_39", "majora_icon_39.png" },
                { "majora_icon_4", "majora_icon_4.png" },
                { "majora_icon_40", "majora_icon_40.png" },
                { "majora_icon_41", "majora_icon_41.png" },
                { "majora_icon_42", "majora_icon_42.png" },
                { "majora_icon_5", "majora_icon_5.png" },
                { "majora_icon_50", "majora_icon_50.png" },
                { "majora_icon_51", "majora_icon_51.png" },
                { "majora_icon_52", "majora_icon_52.png" },
                { "majora_icon_53", "majora_icon_53.png" },
                { "majora_icon_54", "majora_icon_54.png" },
                { "majora_icon_55", "majora_icon_55.png" },
                { "majora_icon_56", "majora_icon_56.png" },
                { "majora_icon_57", "majora_icon_57.png" },
                { "majora_icon_58", "majora_icon_58.png" },
                { "majora_icon_59", "majora_icon_59.png" },
                { "majora_icon_6", "majora_icon_6.png" },
                { "majora_icon_60", "majora_icon_60.png" },
                { "majora_icon_61", "majora_icon_61.png" },
                { "majora_icon_62", "majora_icon_62.png" },
                { "majora_icon_63", "majora_icon_63.png" },
                { "majora_icon_64", "majora_icon_64.png" },
                { "majora_icon_65", "majora_icon_65.png" },
                { "majora_icon_66", "majora_icon_66.png" },
                { "majora_icon_67", "majora_icon_67.png" },
                { "majora_icon_68", "majora_icon_68.png" },
                { "majora_icon_7", "majora_icon_7.png" },
                { "majora_icon_76", "majora_icon_76.png" },
                { "majora_icon_8", "majora_icon_8.png" },
                { "majora_icon_80", "majora_icon_80.png" },
                { "majora_icon_82", "majora_icon_82.png" },
                { "majora_icon_85", "majora_icon_85.png" },
                { "majora_icon_86", "majora_icon_86.png" },
                { "majora_icon_87", "majora_icon_87.png" },
                { "majora_icon_88", "majora_icon_88.png" },
                { "majora_icon_89", "majora_icon_89.png" },
                { "majora_icon_9", "majora_icon_9.png" },
                { "majora_icon_90", "majora_icon_90.png" },
                { "majora_icon_91", "majora_icon_91.png" },
                { "majora_icon_92", "majora_icon_92.png" },
                { "majora_icon_93", "majora_icon_93.png" },
                { "majora_icon_94", "majora_icon_94.png" },
                { "majora_icon_95", "majora_icon_95.png" },
                { "majora_icon_96", "majora_icon_96.png" },
                { "majora_icon_97", "majora_icon_97.png" },
                { "majora_icon_98", "majora_icon_98.png" },
                { "majora_icon_99", "majora_icon_99.png" },
                { "majora_xmes_left", "majora_xmes_left.png" },
                { "majora_xmes_right", "majora_xmes_right.png" },
                { "xmes_left", "xmes_left.png" },
                { "xmes_right", "xmes_right.png" },
            };

        internal static SKBitmap TryGetBitmap(string logicalName)
        {
            if (!NameLookup.TryGetValue(logicalName, out string fileName))
                return null;

            try
            {
                return LoadEmbedded(fileName);
            }
            catch (FileNotFoundException)
            {
                return null;
            }
        }
    }
}
